JavaScriptConteudos/Models/ErrorViewModel.cs
using System;

namespace JavaScriptConteudos.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

JavaScriptConteudos/Controllers/AlterarConteudoHtmlController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JavaScriptConteudos.Controllers
{
    public class AlterarConteudoHtmlController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JavaScriptConteudos/Controllers/HomeController.cs
using JavaScriptConteudos.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace JavaScriptConteudos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

JavaScriptConteudos/Controllers/OperadoresCondicionaisController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JavaScriptConteudos.Controllers
{
    public class OperadoresCondicionaisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

JavaScriptConteudos/Views/AlterarConteudoHtml/Index.cshtml
<h4>Alterar conteúdo Html para completar o nome</h4>
<!-- Exemplo Nº 1 -->
<p id="exemplo">Meu Nome é Relinton</p>

<button class="btn-success" type="button" onclick='document.getElementById("exemplo").innerHTML = "Ops Meu nome é Relinton Pinheiro Franco"'>Alterar Nome</button>

<br />
<br />
<br />
<br />

<h4>Alterar conteúdo Html para Acender e Apagar a Lâmpada</h4>
<!-- Exemplo Nº 2 -->
<button onclick="document.getElementById('imagemlampada1').src='imagemlampada2.gif'">Acender a Lâmpada</button>
<img id="imagemlampada1" src="imagemlampada1.gif" style="width:100px;" />
<button onclick="document.getElementById('imagemlampada1').src='imagemlampada1.gif'">Desligar a Lâmpada</button>

<br />
<br />
<br />
<br />

<h4>Alterar estilo de um conteúdo Html</h4>
<!-- Exemplo Nº 3 -->
<p id="ex3">Lorem Ipsum eu sou o conteúdo.</p>
<button type="button" onclick="document.getElementById('ex3').style.fontSize='35px'">Alterar estilo!</button>

<br />
<br />
<br />
<br />

<h4>Ocultar elementos HTML</h4>
<!-- Exemplo Nº 4 -->
<p id="ex4">Olá, eu sou o conteúdo a ser Ocultado :)</p>
<button type="button" onclick="document.getElementById('ex4').style.display='none'">Ocultar o conteúdo!</button>

<br />
<br />
<br />
<br />

<h4>Mostrar elementos HTML ocultos.</h4>
<!-- Exemplo Nº 5 -->
<p id="ex5" style="display:none">Olá, eu estava ocultado para você!</p>
<button type="button" onclick="document.getElementById('ex5').style.display='block'">Mostrar elemento Oculto!</button>

<br />
<br />
<br />
<br />

<h4>Alterar conteúdo Html por meio de Functions</h4>
<!-- Exemplo Nº 6 -->
<script>
    function AlterarHtmlFunction() {
        document.getElementById("ex6").innerHTML = "Nome completo é: Relinton Pinheiro Franco"
    }
</script>
<p id="ex6">Meu nome é Relinton</p>
<button type="button" onclick="AlterarHtmlFunction()">Ver Nome Completo</button>

<br />
<br />
<br />
<br />

<h4>Acrescentar conteúdo mais soma</h4>
<!-- Exemplo Nº 7 -->
<p id="ex7"></p>

<script>
    document.getElementById("ex7").innerHTML = 5 + 2;
</script>


<br />
<br />
<br />
<br />

<h4>Declarações JavaScript</h4>
<!-- Exemplo Nº 8 -->

<p id="ex8"></p>

<script>
    let x, y, z;
    x = 5;
    y = 2;
    z = x + y;

    document.getElementById("ex8").innerHTML = "O valor de Z é " + z + ".";
</script>



<br />
<br />
<br />
<br />

<h4>Objetos JavaScript podem conter muitos valores.</h4>
<!-- Exemplo Nº 9 -->
<p id="ex9"></p>
<script>
    const carro = { type: "Fiat", model: "500", color: "white" };
    document.getElementById("ex9").innerHTML = "O tipo do carro é " + carro.type;
</script>

<br />
<br />
<br />
<br />

<h4>Acessar propriedades do Objeto.</h4>
<!-- Exemplo Nº 10 -->
<p id="ex10"></p>
<script>
    const pessoa = {
        primeiroNome: "Relinton",
        ultimoNome: "Pinheiro Franco",
        id: 2022
    };

    document.getElementById("ex10").innerHTML =
        pessoa["primeiroNome"] + " " + pessoa["ultimoNome"];
</script>

<br />
<br />
<br />
<br />

<h4>Acessar propriedades do Objeto com Function.</h4>
<!-- Exemplo Nº 11 -->
<p id="ex10"></p>
<script>
    const pessoa = {
        primeiroNome: "Relinton",
        ultimoNome: "Pinheiro Franco",
        id: 2022,
        nomeCompleto: function () {
            return this.primeiroNome + " " + this.ultimoNome;
        }
    };
</script>


<br />
<br />
<br />
<br />

<h4>Acessar propriedades do Objeto com Function.</h4>
<!-- Exemplo Nº 12 -->
<button onclick="displayDate()">Verificar data</button>

<script>
    function displayDate() {
        document.getElementById("ex12").innerHTML = Date();
    }
</script>

<p id="ex12"></p>


<br />
<br />
<br />
<br />

<h4>A propriedade length retorna o comprimento de uma string.</h4>
<!-- Exemplo Nº 13 -->
<p id="ex13"></p>

<script>
    let text = "Relinton";
    document.getElementById("ex13").innerHTML = text.length;
</script>

JavaScriptConteudos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<style>
    body {
        font-family: Arial;
    }

    /* Style the tab */
    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

        /* Style the buttons inside the tab */
        .tab button {
            background-color: inherit;
            float: left;
            border: none;
            outline: none;
            cursor: pointer;
            padding: 14px 16px;
            transition: 0.3s;
            font-size: 17px;
        }

            /* Change background color of buttons on hover */
            .tab button:hover {
                background-color: #ddd;
            }

            /* Create an active/current tablink class */
            .tab button.active {
                background-color: #ccc;
            }

    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>

<h2>Tabs</h2>
<p>Click on the buttons inside the tabbed menu:</p>

<div class="tab">
    <button class="tablinks" onclick="openCity(event, 'London')">London</button>
    <button class="tablinks" onclick="openCity(event, 'Paris')">Paris</button>
    <button class="tablinks" onclick="openCity(event, 'Tokyo')">Tokyo</button>
</div>

<div id="London" class="tabcontent">
    <h3>London</h3>
    <p>London is the capital city of England.</p>
</div>

<div id="Paris" class="tabcontent">
    <h3>Paris</h3>
    <p>Paris is the capital of France.</p>
</div>

<div id="Tokyo" class="tabcontent">
    <h3>Tokyo</h3>
    <p>Tokyo is the capital of Japan.</p>
</div>

<script>
    function openCity(evt, cityName) {
        var i, tabcontent, tablinks;
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }
        document.getElementById(cityName).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>

JavaScriptConteudos/Views/OperadoresCondicionais/Index.cshtml
<h4>Comparação JavaScript</h4>
<!-- Exemplo Nº 1 -->
<p>Insira sua idade e clique no botão:</p>
<input id="idade" value="" />

<button onclick="verificarIdade()">Verificar</button>

<p id="ex1"></p>

<script>
    function verificarIdade() {
        let idade = document.getElementById("idade").value;
        let votacao = (idade < 18) ? "Muito jovem para votar." : "Idade suficiente para votar";
        document.getElementById("ex1").innerHTML = votacao + " votar.";
    }
</script>


<br />
<br />
<br />
<br />

<h4>Condição If</h4>
<!-- Exemplo Nº 2 -->

<p>Exibir "Bom dia!" se a hora for inferior às 18:00:</p>
<p id="ex2"></p>
<script>
    const hora = new Date().getHours();
    let saudacao;

    if (hora < 18) {
        saudacao = "Bom dia";
    } else {
        saudacao = "Boa noite";
    }

    document.getElementById("ex2").innerHTML = saudacao;
</script>

<br />
<br />
<br />
<br />

<h4>Interruptor de JavaScript</h4>
<!-- Exemplo Nº 3 -->
<p id="ex3"></p>
<script>
    let dia;
    switch (new Date().getDay()) {
        case 0:
            dia = "Domingo";
            break;
        case 1:
            dia = "Segunda-Feira";
            break;
        case 2:
            dia = "Terça-Feira";
            break;
        case 3:
            dia = "Quarta-Feira";
            break;
        case 4:
            dia = "Quinta-Feira";
            break;
        case 5:
            dia = "Sexta-Feira";
            break;
        case 6:
            dia = "Sábado";
    }
    document.getElementById("ex3").innerHTML = "Hoje é " + dia;
</script>

<br />
<br />
<br />
<br />

<h4>JavaScript For</h4>
<!-- Exemplo Nº 4 -->
<p id="ex4"></p>
<script>
    const carros = ["BMW", "Volvo", "Saab", "Ford", "Fiat", "Audi"];

    let texto = "";
    for (let i = 0; i < carros.length; i++) {
        texto += carros[i] + "<br>";
    }

    document.getElementById("ex4").innerHTML = texto;
</script>

JavaScriptConteudos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - JavaScriptConteudos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">JavaScriptConteudos</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AlterarConteudoHtml" asp-action="Index">Alterar Conteúdo Html</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - JavaScriptConteudos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>